config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  get 'profiles/index'

  get 'homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/contacts/index.html.erb
<div class="container">
      <div class="col-sm-3">
      	<h2>Riku Kiranatama</h2>
      	<%= image_tag("profile.jpg", class: "img-circle") %>
      </div>
      <div class="col-sm-8">
      	<%= form_tag('', class: "form-horizontal") do -%>
      	  <div class="form-group">
      	  	<%= label_tag('inputEmail', 'Email', class: "col-sm-4 control-label") -%>
            <div class="col-sm-8">
              <%= email_field_tag('inputEmail', nil, class: "form-control", placeholder: "Email Anda") -%>
            </div>
          </div>
          <div class="form-group">
          	<%= label_tag('inputMessages', 'Messages', class: "col-sm-4 control-label") -%>
            <div class="col-sm-8">
              <%= text_area_tag('inputMessages', nil, class: "form-control", placeholder: "Messages Anda", rows: "8") -%>
            </div>
          </div>
		  <div class="form-group">
            <div class="col-sm-8">
            	<%= button_tag('Submit', name:"submit", class:"btn btn-default") -%>
            </div>
          </div>
		<% end -%>
      </div>
    </div>

app/views/homes/index.html.erb
    <div class="container">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item active">
          	<%= image_tag("laut.jpg", alt: "Laut di Kota Bandung") %>
            <div class="carousel-caption">
              Laut di Kota Bandung
            </div>
          </div>
          <div class="item">
          	<%= image_tag("langit.jpg", alt: "Laut di Kota Bandung") %>
            <div class="carousel-caption">
              Langit di Kota Bandung
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <p>Hello saya Riku dan saya saat ini akan lulus dari kuliah, salam kenal ya. 
        		Berikut contoh dari hasil design grafik yang saya buat :). </p>
        </div>
        <div class="col-sm-2 pull-right">
            <p>Facebook: riku@mail.com</p>
            <p>Twitter: riku@mail.com</p>	
            <p>Telpon: 022-232392</p>
            <p>Alamat: Jl. Harapan Bangas No.23, Bandung, Indonesia</p>
        </div>
      </div>
     </div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Implement Boostrap with Ruby on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Training Bootstrap", homes_index_path, class: "navbar-brand" %>
        </div>	
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home", homes_index_path %></li>
            <li><%= link_to "Profile", profiles_index_path %></li>
            <li><%= link_to "Contact", contacts_index_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    
    
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
	<div class="container">
      <div class="col-sm-3">
      	<h2>Riku Kiranatama</h2>
      	<%= image_tag("profile.jpg", class: "img-circle") %>
      </div>
      <div class="col-sm-8">
      	<table class="table table-striped">
      	  <tbody>
      	    <tr>
      		  <td>Nama</td>
      		  <td>Riku Kiranatama</td>
      		</tr>
      	    <tr>
      		  <td>Tempat, Tangggal Lahir</td>
      		  <td>Bandung, 7 Oktober 1989</td>
      		</tr>
      	    <tr>
      		  <td>Jenis Kelamin</td>
      		  <td>Pria</td>
      		</tr>
      	    <tr>
      		  <td>Alamat Domisili</td>
      		  <td>Jl. Soekarno Hatta no. 104</td>
      		</tr>
      	  </tbody>
      	</table>
      </div>
    </div>